// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddNewCustomItem(arg1:database.CustomUPCModel):Promise<void>;

export function CheckBuildNumber():Promise<number>;

export function CheckLogin(arg1:string,arg2:string):Promise<boolean>;

export function DeleteInventoryItem(arg1:string):Promise<void>;

export function EditClient(arg1:database.User):Promise<boolean>;

export function GetInventoryItems():Promise<Array<database.ItemDataModel>>;

export function GetServiceSettings():Promise<database.ServiceSettings>;

export function GetUserTableInfo():Promise<Array<database.User>>;

export function ScanCancel(arg1:string):Promise<void>;

export function ScanInHandler(arg1:database.ScanInRequest):Promise<database.ScanInResponse>;

export function ScanOutCancel(arg1:string):Promise<void>;

export function ScanOutHandler(arg1:database.ScanInRequest):Promise<database.ScanInResponse>;

export function SetNewServiceSettings(arg1:database.ServiceSettings):Promise<void>;

export function SetNewUser(arg1:database.User):Promise<boolean>;
