// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNewCustomItem(arg1) {
  return window['go']['main']['App']['AddNewCustomItem'](arg1);
}

export function CheckBuildNumber() {
  return window['go']['main']['App']['CheckBuildNumber']();
}

export function CheckLogin(arg1, arg2) {
  return window['go']['main']['App']['CheckLogin'](arg1, arg2);
}

export function DeleteInventoryItem(arg1) {
  return window['go']['main']['App']['DeleteInventoryItem'](arg1);
}

export function EditClient(arg1) {
  return window['go']['main']['App']['EditClient'](arg1);
}

export function GetInventoryItems() {
  return window['go']['main']['App']['GetInventoryItems']();
}

export function GetServiceSettings() {
  return window['go']['main']['App']['GetServiceSettings']();
}

export function GetUserTableInfo() {
  return window['go']['main']['App']['GetUserTableInfo']();
}

export function ScanCancel(arg1) {
  return window['go']['main']['App']['ScanCancel'](arg1);
}

export function ScanInHandler(arg1) {
  return window['go']['main']['App']['ScanInHandler'](arg1);
}

export function ScanOutCancel(arg1) {
  return window['go']['main']['App']['ScanOutCancel'](arg1);
}

export function ScanOutHandler(arg1) {
  return window['go']['main']['App']['ScanOutHandler'](arg1);
}

export function SetNewServiceSettings(arg1) {
  return window['go']['main']['App']['SetNewServiceSettings'](arg1);
}

export function SetNewUser(arg1) {
  return window['go']['main']['App']['SetNewUser'](arg1);
}
